version: '3.4'

services:
  postgres:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=new_user
      - POSTGRES_PASSWORD=new_password
      - POSTGRES_DB=db
  flyway:
    image: flyway/flyway:6.3.1
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./sql_versions:/flyway/sql
      - ./config/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres